<?php

namespace Database\Seeders;

use App\Enums\TradeDirection;
use App\Enums\TradeOutcome;
use App\Enums\TradeType;
use App\Models\Portfolio;
use App\Models\Strategy;
use App\Models\Trade;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class TradeSeeder extends Seeder
{
    public function run(): void
    {
        $portfolio = Portfolio::where('name', 'Forex Live Account')->first();
        $cryptoPortfolio = Portfolio::where('name', 'Crypto Swing Account')->first();

        $strategies = Strategy::all()->keyBy('name');

        $trades = [
            // --- Forex trades (portfolio 1) ---
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Breakout Momentum']->id,
                'pair' => 'EUR/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 1.08450,
                'exit_price' => 1.08920,
                'size' => 0.50,
                'stop_loss' => 1.08200,
                'take_profit' => 1.09000,
                'pnl_amount' => 235.00,
                'pnl_pips' => 47.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Breakout Momentum',
                'notes' => 'Strong breakout dari resistance 1.0840. Momentum bagus, close di TP.',
                'entry_date' => Carbon::now()->subDays(28)->setTime(9, 15),
                'exit_date' => Carbon::now()->subDays(28)->setTime(14, 30),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Supply & Demand Zone']->id,
                'pair' => 'GBP/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 1.27100,
                'exit_price' => 1.26650,
                'size' => 0.30,
                'stop_loss' => 1.27400,
                'take_profit' => 1.26600,
                'pnl_amount' => 135.00,
                'pnl_pips' => 45.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Supply & Demand Zone',
                'notes' => 'Rejection di supply zone, bearish engulfing M15.',
                'entry_date' => Carbon::now()->subDays(26)->setTime(10, 0),
                'exit_date' => Carbon::now()->subDays(26)->setTime(16, 45),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Trend Following EMA']->id,
                'pair' => 'USD/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 157.250,
                'exit_price' => 156.980,
                'size' => 0.20,
                'stop_loss' => 156.900,
                'take_profit' => 157.800,
                'pnl_amount' => -54.00,
                'pnl_pips' => -27.0,
                'outcome' => TradeOutcome::LOSS,
                'fees' => 3.50,
                'strategy' => 'Trend Following EMA',
                'notes' => 'SL kena saat NFP spike. Seharusnya skip news besar.',
                'entry_date' => Carbon::now()->subDays(24)->setTime(8, 30),
                'exit_date' => Carbon::now()->subDays(24)->setTime(8, 35),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Liquidity Grab']->id,
                'pair' => 'EUR/GBP',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 0.84620,
                'exit_price' => 0.84980,
                'size' => 0.40,
                'stop_loss' => 0.84450,
                'take_profit' => 0.85000,
                'pnl_amount' => 144.00,
                'pnl_pips' => 36.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Liquidity Grab',
                'notes' => 'Fakey di bawah support, langsung reversal. Perfect liquidity grab.',
                'entry_date' => Carbon::now()->subDays(22)->setTime(13, 0),
                'exit_date' => Carbon::now()->subDays(22)->setTime(17, 20),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Scalping M15']->id,
                'pair' => 'AUD/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 0.65820,
                'exit_price' => 0.65710,
                'size' => 0.60,
                'stop_loss' => 0.65950,
                'take_profit' => 0.65680,
                'pnl_amount' => 66.00,
                'pnl_pips' => 11.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Scalping M15',
                'notes' => 'BB squeeze release ke bawah, RSI divergence bearish.',
                'entry_date' => Carbon::now()->subDays(20)->setTime(7, 45),
                'exit_date' => Carbon::now()->subDays(20)->setTime(8, 30),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Breakout Momentum']->id,
                'pair' => 'USD/CAD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 1.36400,
                'exit_price' => 1.36150,
                'size' => 0.35,
                'stop_loss' => 1.36100,
                'take_profit' => 1.36900,
                'pnl_amount' => -87.50,
                'pnl_pips' => -25.0,
                'outcome' => TradeOutcome::LOSS,
                'fees' => 3.50,
                'strategy' => 'Breakout Momentum',
                'notes' => 'False breakout, langsung reversal. Patience kurang.',
                'entry_date' => Carbon::now()->subDays(18)->setTime(11, 0),
                'exit_date' => Carbon::now()->subDays(18)->setTime(12, 15),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Supply & Demand Zone']->id,
                'pair' => 'NZD/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 0.59850,
                'exit_price' => 0.60180,
                'size' => 0.45,
                'stop_loss' => 0.59600,
                'take_profit' => 0.60200,
                'pnl_amount' => 148.50,
                'pnl_pips' => 33.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Supply & Demand Zone',
                'notes' => 'Demand zone bounce, bullish pin bar M30.',
                'entry_date' => Carbon::now()->subDays(16)->setTime(6, 0),
                'exit_date' => Carbon::now()->subDays(16)->setTime(15, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Trend Following EMA']->id,
                'pair' => 'EUR/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 171.800,
                'exit_price' => 171.800,
                'size' => 0.25,
                'stop_loss' => 172.100,
                'take_profit' => 171.200,
                'pnl_amount' => 0.00,
                'pnl_pips' => 0.0,
                'outcome' => TradeOutcome::BREAKEVEN,
                'fees' => 3.50,
                'strategy' => 'Trend Following EMA',
                'notes' => 'Movements sideways, close di breakeven untuk hindari loss.',
                'entry_date' => Carbon::now()->subDays(14)->setTime(9, 0),
                'exit_date' => Carbon::now()->subDays(14)->setTime(18, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Scalping M15']->id,
                'pair' => 'GBP/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 192.450,
                'exit_price' => 192.780,
                'size' => 0.20,
                'stop_loss' => 192.200,
                'take_profit' => 192.800,
                'pnl_amount' => 66.00,
                'pnl_pips' => 33.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Scalping M15',
                'notes' => 'Clean setup, BB squeeze breakout ke atas.',
                'entry_date' => Carbon::now()->subDays(12)->setTime(8, 0),
                'exit_date' => Carbon::now()->subDays(12)->setTime(9, 45),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Liquidity Grab']->id,
                'pair' => 'EUR/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 1.09200,
                'exit_price' => 1.08850,
                'size' => 0.40,
                'stop_loss' => 1.09450,
                'take_profit' => 1.08800,
                'pnl_amount' => 140.00,
                'pnl_pips' => 35.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Liquidity Grab',
                'notes' => 'Sweep high lalu langsung dump. Classic stop hunt.',
                'entry_date' => Carbon::now()->subDays(10)->setTime(14, 0),
                'exit_date' => Carbon::now()->subDays(10)->setTime(16, 30),
            ],
            // --- More forex ---
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Breakout Momentum']->id,
                'pair' => 'USD/CHF',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 0.89200,
                'exit_price' => 0.88950,
                'size' => 0.30,
                'stop_loss' => 0.89450,
                'take_profit' => 0.88900,
                'pnl_amount' => 75.00,
                'pnl_pips' => 25.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Breakout Momentum',
                'notes' => 'Break support dengan momentum kuat.',
                'entry_date' => Carbon::now()->subDays(9)->setTime(10, 30),
                'exit_date' => Carbon::now()->subDays(9)->setTime(14, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Supply & Demand Zone']->id,
                'pair' => 'AUD/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 107.500,
                'exit_price' => 107.150,
                'size' => 0.25,
                'stop_loss' => 107.200,
                'take_profit' => 108.000,
                'pnl_amount' => -87.50,
                'pnl_pips' => -35.0,
                'outcome' => TradeOutcome::LOSS,
                'fees' => 3.50,
                'strategy' => 'Supply & Demand Zone',
                'notes' => 'Demand zone tidak hold, langsung break ke bawah.',
                'entry_date' => Carbon::now()->subDays(8)->setTime(7, 30),
                'exit_date' => Carbon::now()->subDays(8)->setTime(11, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Trend Following EMA']->id,
                'pair' => 'GBP/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 1.26800,
                'exit_price' => 1.27350,
                'size' => 0.35,
                'stop_loss' => 1.26500,
                'take_profit' => 1.27400,
                'pnl_amount' => 192.50,
                'pnl_pips' => 55.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Trend Following EMA',
                'notes' => 'Perfect pullback to EMA20, trend naik kuat.',
                'entry_date' => Carbon::now()->subDays(7)->setTime(9, 30),
                'exit_date' => Carbon::now()->subDays(7)->setTime(16, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Scalping M15']->id,
                'pair' => 'EUR/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 1.09100,
                'exit_price' => 1.08980,
                'size' => 0.50,
                'stop_loss' => 1.09250,
                'take_profit' => 1.08950,
                'pnl_amount' => 60.00,
                'pnl_pips' => 12.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Scalping M15',
                'notes' => 'Quick scalp, RSI overbought reject.',
                'entry_date' => Carbon::now()->subDays(5)->setTime(13, 15),
                'exit_date' => Carbon::now()->subDays(5)->setTime(13, 45),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Liquidity Grab']->id,
                'pair' => 'USD/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 156.800,
                'exit_price' => 157.200,
                'size' => 0.30,
                'stop_loss' => 156.500,
                'take_profit' => 157.300,
                'pnl_amount' => 120.00,
                'pnl_pips' => 40.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Liquidity Grab',
                'notes' => 'Sweep low session lalu reversal cepat.',
                'entry_date' => Carbon::now()->subDays(4)->setTime(6, 0),
                'exit_date' => Carbon::now()->subDays(4)->setTime(10, 30),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Breakout Momentum']->id,
                'pair' => 'AUD/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 0.66100,
                'exit_price' => 0.65800,
                'size' => 0.40,
                'stop_loss' => 0.65850,
                'take_profit' => 0.66500,
                'pnl_amount' => -120.00,
                'pnl_pips' => -30.0,
                'outcome' => TradeOutcome::LOSS,
                'fees' => 3.50,
                'strategy' => 'Breakout Momentum',
                'notes' => 'False breakout, market reversal setelah entry.',
                'entry_date' => Carbon::now()->subDays(3)->setTime(11, 0),
                'exit_date' => Carbon::now()->subDays(3)->setTime(13, 30),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Supply & Demand Zone']->id,
                'pair' => 'GBP/JPY',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 193.200,
                'exit_price' => 192.700,
                'size' => 0.20,
                'stop_loss' => 193.500,
                'take_profit' => 192.700,
                'pnl_amount' => 100.00,
                'pnl_pips' => 50.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Supply & Demand Zone',
                'notes' => 'Supply zone rejection, double top pattern.',
                'entry_date' => Carbon::now()->subDays(2)->setTime(14, 30),
                'exit_date' => Carbon::now()->subDays(2)->setTime(17, 0),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Trend Following EMA']->id,
                'pair' => 'EUR/USD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 1.08700,
                'exit_price' => 1.09150,
                'size' => 0.35,
                'stop_loss' => 1.08400,
                'take_profit' => 1.09200,
                'pnl_amount' => 157.50,
                'pnl_pips' => 45.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Trend Following EMA',
                'notes' => 'Clean pullback entry, strong bullish momentum.',
                'entry_date' => Carbon::now()->subDays(1)->setTime(9, 0),
                'exit_date' => Carbon::now()->subDays(1)->setTime(15, 30),
            ],
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Scalping M15']->id,
                'pair' => 'USD/CAD',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 1.36500,
                'exit_price' => 1.36350,
                'size' => 0.50,
                'stop_loss' => 1.36700,
                'take_profit' => 1.36300,
                'pnl_amount' => 75.00,
                'pnl_pips' => 15.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 3.50,
                'strategy' => 'Scalping M15',
                'notes' => 'BB upper band reject, quick scalp profit.',
                'entry_date' => Carbon::now()->subHours(18)->setTime(10, 0),
                'exit_date' => Carbon::now()->subHours(16)->setTime(11, 30),
            ],
            // --- Open trade ---
            [
                'portfolio_id' => $portfolio->id,
                'strategy_id' => $strategies['Liquidity Grab']->id,
                'pair' => 'EUR/GBP',
                'trade_type' => TradeType::FOREX,
                'direction' => TradeDirection::LONG,
                'entry_price' => 0.84750,
                'exit_price' => null,
                'size' => 0.30,
                'stop_loss' => 0.84500,
                'take_profit' => 0.85100,
                'pnl_amount' => 0,
                'pnl_pips' => null,
                'outcome' => TradeOutcome::OPEN,
                'fees' => 0,
                'strategy' => 'Liquidity Grab',
                'notes' => 'Setup liquidity grab di session low. Masih hold.',
                'entry_date' => Carbon::now()->subHours(4)->setTime(8, 0),
                'exit_date' => null,
            ],
            // --- Crypto trades (portfolio 2) ---
            [
                'portfolio_id' => $cryptoPortfolio->id,
                'strategy_id' => $strategies['Breakout Momentum']->id,
                'pair' => 'BTC/USDT',
                'trade_type' => TradeType::CRYPTO,
                'direction' => TradeDirection::LONG,
                'entry_price' => 67500.00,
                'exit_price' => 69200.00,
                'size' => 0.05,
                'stop_loss' => 66000.00,
                'take_profit' => 69500.00,
                'pnl_amount' => 85.00,
                'pnl_pips' => 1700.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 5.00,
                'strategy' => 'Breakout Momentum',
                'notes' => 'BTC breakout dari range 65k-67k. Strong momentum.',
                'entry_date' => Carbon::now()->subDays(15)->setTime(20, 0),
                'exit_date' => Carbon::now()->subDays(13)->setTime(8, 0),
            ],
            [
                'portfolio_id' => $cryptoPortfolio->id,
                'strategy_id' => $strategies['Trend Following EMA']->id,
                'pair' => 'ETH/USDT',
                'trade_type' => TradeType::CRYPTO,
                'direction' => TradeDirection::SHORT,
                'entry_price' => 3450.00,
                'exit_price' => 3380.00,
                'size' => 0.50,
                'stop_loss' => 3520.00,
                'take_profit' => 3350.00,
                'pnl_amount' => 35.00,
                'pnl_pips' => 70.0,
                'outcome' => TradeOutcome::WIN,
                'fees' => 4.00,
                'strategy' => 'Trend Following EMA',
                'notes' => 'ETH downtrend, entry saat pullback ke EMA.',
                'entry_date' => Carbon::now()->subDays(11)->setTime(14, 0),
                'exit_date' => Carbon::now()->subDays(9)->setTime(6, 0),
            ],
            [
                'portfolio_id' => $cryptoPortfolio->id,
                'strategy_id' => $strategies['Liquidity Grab']->id,
                'pair' => 'SOL/USDT',
                'trade_type' => TradeType::CRYPTO,
                'direction' => TradeDirection::LONG,
                'entry_price' => 172.50,
                'exit_price' => 168.00,
                'size' => 10,
                'stop_loss' => 167.00,
                'take_profit' => 180.00,
                'pnl_amount' => -45.00,
                'pnl_pips' => -4.5,
                'outcome' => TradeOutcome::LOSS,
                'fees' => 3.00,
                'strategy' => 'Liquidity Grab',
                'notes' => 'Fake reversal, SL kena. Market masih bearish.',
                'entry_date' => Carbon::now()->subDays(7)->setTime(22, 0),
                'exit_date' => Carbon::now()->subDays(6)->setTime(3, 0),
            ],
        ];

        foreach ($trades as $trade) {
            Trade::create($trade);
        }
    }
}
